In [2]:
import os
os.getcwd()

'C:\\Users\\Geoff\\Documents\\CU Boulder MSDS\\DTSA 5304 - Data Visualization\\Final Project'

In [3]:
from pathlib import Path

Path("data/raw").mkdir(parents=True, exist_ok=True)
Path("data/processed").mkdir(parents=True, exist_ok=True)

In [4]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\Geoff\Documents\CU Boulder MSDS\DTSA 5304 - Data Visualization\Final Project
['.git', '.gitignore', '.ipynb_checkpoints', 'ap_visualization.ipynb', 'data', 'prepare_data.ipynb', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb']

In [5]:
import pandas as pd

In [6]:
participation = pd.read_excel(
    "data/raw/ap-admin-report-2025-participation.xlsx"
)

In [7]:
import pandas as pd

In [8]:
participation = pd.read_excel(
    "data/raw/ap-admin-report-2025-participation.xlsx"
)

In [9]:
participation.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,AP Participation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,"Percentage of HS students in Grades 10, 11, an...",NaN,NaN,NaN,Total AP Examinees,NaN,NaN,NaN,"One-, Five-, and Ten-Year Growth Rates of AP E...",NaN,NaN
3,NaN,NaN,2025,2024,2020,2015.00,2025,2024,2020,2015,2024-2025,2020-2025,2015-2025
4,NaN,National,0.22,0.21,0.19,0.17,2780636,2648896,2293553,2091688,0.049734,0.212371,0.329374

In [10]:
participation = pd.read_excel(
    "data/raw/ap-admin-report-2025-participation.xlsx",
    header=3
)

participation.head(10)

,Unnamed: 0,Unnamed: 1,"Percentage of HS students in Grades 10, 11, and 12 who took AP Exams",Unnamed: 3,Unnamed: 4,Unnamed: 5,Total AP Examinees,Unnamed: 7,Unnamed: 8,Unnamed: 9,"One-, Five-, and Ten-Year Growth Rates of AP Examinees",Unnamed: 11,Unnamed: 12
0,NaN,NaN,2025,2024,2020,2015.00,2025,2024,2020,2015,2024-2025,2020-2025,2015-2025
1,NaN,National,0.22,0.21,0.19,0.17,2780636,2648896,2293553,2091688,0.049734,0.212371,0.329374
2,NaN,By examinee race/ethnicity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Asian,0.54,0.52,0.44,0.43,394760,375469,305099,264417,0.051378,0.293875,0.492945
4,NaN,Hispanic/Latino,0.19,0.18,0.16,0.15,730720,691650,535891,412389,0.056488,0.363561,0.771919
5,NaN,White,0.2,0.2,0.19,0.19,1136422,1112326,1100785,1151665,0.021663,0.032374,-0.013236
6,NaN,Black/African American,0.12,0.12,0.09,0.10,228974,215727,153001,179150,0.061406,0.496552,0.278113
7,NaN,American Indian/Alaska Native,0.07,0.08,0.1,0.10,7684,8399,12814,11887,-0.085129,-0.400343,-0.35358
8,NaN,Native Hawaiian or Other Pacific Islander,0.08,0.08,0.08,NaN,3826,3648,3692,NaN,0.048794,0.036295,NaN
9,NaN,Two or More Races,0.2,0.2,0.25,NaN,126640,118729,105535,NaN,0.066631,0.199981,NaN

In [11]:
participation.columns

Index(['Unnamed: 0', 'Unnamed: 1',
       'Percentage of HS students in Grades 10, 11, and 12 who took AP Exams',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Total AP Examinees',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'One-, Five-, and Ten-Year Growth Rates of AP Examinees', 'Unnamed: 11',
       'Unnamed: 12'],
      dtype='str')

In [12]:
participation.columns = [
    "blank",
    "state",
    "participation_2025",
    "participation_2024",
    "participation_2020",
    "participation_2015",
    "examinees_2025",
    "examinees_2024",
    "examinees_2020",
    "examinees_2015",
    "growth_1yr",
    "growth_5yr",
    "growth_10yr"
]

participation.head(10)

,blank,state,participation_2025,participation_2024,participation_2020,participation_2015,examinees_2025,examinees_2024,examinees_2020,examinees_2015,growth_1yr,growth_5yr,growth_10yr
0,NaN,NaN,2025,2024,2020,2015.00,2025,2024,2020,2015,2024-2025,2020-2025,2015-2025
1,NaN,National,0.22,0.21,0.19,0.17,2780636,2648896,2293553,2091688,0.049734,0.212371,0.329374
2,NaN,By examinee race/ethnicity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Asian,0.54,0.52,0.44,0.43,394760,375469,305099,264417,0.051378,0.293875,0.492945
4,NaN,Hispanic/Latino,0.19,0.18,0.16,0.15,730720,691650,535891,412389,0.056488,0.363561,0.771919
5,NaN,White,0.2,0.2,0.19,0.19,1136422,1112326,1100785,1151665,0.021663,0.032374,-0.013236
6,NaN,Black/African American,0.12,0.12,0.09,0.10,228974,215727,153001,179150,0.061406,0.496552,0.278113
7,NaN,American Indian/Alaska Native,0.07,0.08,0.1,0.10,7684,8399,12814,11887,-0.085129,-0.400343,-0.35358
8,NaN,Native Hawaiian or Other Pacific Islander,0.08,0.08,0.08,NaN,3826,3648,3692,NaN,0.048794,0.036295,NaN
9,NaN,Two or More Races,0.2,0.2,0.25,NaN,126640,118729,105535,NaN,0.066631,0.199981,NaN

In [13]:
participation.columns = [
    "blank",
    "state_or_group",
    "participation_2025",
    "participation_2024",
    "participation_2020",
    "participation_2015",
    "examinees_2025",
    "examinees_2024",
    "examinees_2020",
    "examinees_2015",
    "growth_1yr",
    "growth_5yr",
    "growth_10yr"
]

participation.head(10)

,blank,state_or_group,participation_2025,participation_2024,participation_2020,participation_2015,examinees_2025,examinees_2024,examinees_2020,examinees_2015,growth_1yr,growth_5yr,growth_10yr
0,NaN,NaN,2025,2024,2020,2015.00,2025,2024,2020,2015,2024-2025,2020-2025,2015-2025
1,NaN,National,0.22,0.21,0.19,0.17,2780636,2648896,2293553,2091688,0.049734,0.212371,0.329374
2,NaN,By examinee race/ethnicity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Asian,0.54,0.52,0.44,0.43,394760,375469,305099,264417,0.051378,0.293875,0.492945
4,NaN,Hispanic/Latino,0.19,0.18,0.16,0.15,730720,691650,535891,412389,0.056488,0.363561,0.771919
5,NaN,White,0.2,0.2,0.19,0.19,1136422,1112326,1100785,1151665,0.021663,0.032374,-0.013236
6,NaN,Black/African American,0.12,0.12,0.09,0.10,228974,215727,153001,179150,0.061406,0.496552,0.278113
7,NaN,American Indian/Alaska Native,0.07,0.08,0.1,0.10,7684,8399,12814,11887,-0.085129,-0.400343,-0.35358
8,NaN,Native Hawaiian or Other Pacific Islander,0.08,0.08,0.08,NaN,3826,3648,3692,NaN,0.048794,0.036295,NaN
9,NaN,Two or More Races,0.2,0.2,0.25,NaN,126640,118729,105535,NaN,0.066631,0.199981,NaN

In [14]:
participation[["state_or_group", "participation_2025", "examinees_2025"]].head(40)

,state_or_group,participation_2025,examinees_2025
0,NaN,2025,2025
1,National,0.22,2780636
2,By examinee race/ethnicity,NaN,NaN
3,Asian,0.54,394760
4,Hispanic/Latino,0.19,730720
5,White,0.2,1136422
6,Black/African American,0.12,228974
7,American Indian/Alaska Native,0.07,7684
8,Native Hawaiian or Other Pacific Islander,0.08,3826
9,Two or More Races,0.2,126640
10,No Response,NaN,151610
11,NaN,NaN,NaN
12,Alabama,0.15,28817
13,Asian,0.51,1559
14,Hispanic/Latino,0.15,3196
15,White,0.18,16888
16,Black/African American,0.08,4675
17,American Indian/Alaska Native,0.08,146
18,Native Hawaiian or Other Pacific Islander,0.11,23
19,Two or More Races,0.21,1315
20,No Response,NaN,1015
21,NaN,NaN,NaN
22,Alaska,0.14,4462
23,Asian,0.22,368
24,Hispanic/Latino,0.17,413
25,White,0.18,2710
26,Black/African American,0.12,80
27,American Indian/Alaska Native,0.03,204
28,Native Hawaiian or Other Pacific Islander,0.03,30
29,Two or More Races,0.12,489
30,No Response,NaN,168
31,NaN,NaN,NaN
32,Arizona,0.15,44887
33,Asian,0.5,5229
34,Hispanic/Latino,0.11,16812
35,White,0.16,16684
36,Black/African American,0.1,1769
37,American Indian/Alaska Native,0.04,540
38,Native Hawaiian or Other Pacific Islander,0.08,79
39,Two or More Races,0.16,2328

In [15]:
states = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California",
    "Colorado", "Connecticut", "Delaware", "District of Columbia",
    "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana",
    "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
    "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri",
    "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
    "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
    "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island",
    "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah",
    "Vermont", "Virginia", "Washington", "West Virginia",
    "Wisconsin", "Wyoming"
]

participation_states = participation[
    participation["state_or_group"].isin(states)
].copy()

participation_states.head()

,blank,state_or_group,participation_2025,participation_2024,participation_2020,participation_2015,examinees_2025,examinees_2024,examinees_2020,examinees_2015,growth_1yr,growth_5yr,growth_10yr
12,NaN,Alabama,0.15,0.15,0.12,0.14,28817,27996,21104,23371,0.029326,0.365476,0.233024
22,NaN,Alaska,0.14,0.13,0.1,0.11,4462,4110,2823,3187,0.085645,0.580588,0.400063
32,NaN,Arizona,0.15,0.14,0.11,0.12,44887,42606,33635,31799,0.053537,0.334532,0.411585
42,NaN,Arkansas,0.24,0.23,0.19,0.24,29361,27777,21262,25420,0.057026,0.380914,0.155035
52,NaN,California,0.27,0.25,0.23,0.20,407095,388819,355285,316529,0.047004,0.145827,0.286122

In [16]:
participation_states = participation_states[
    [
        "state_or_group",
        "participation_2025",
        "participation_2024",
        "participation_2020",
        "participation_2015",
        "examinees_2025",
        "examinees_2024",
        "examinees_2020",
        "examinees_2015"
    ]
].copy()

participation_states = participation_states.rename(
    columns={"state_or_group": "state"}
)

participation_states.head()

,state,participation_2025,participation_2024,participation_2020,participation_2015,examinees_2025,examinees_2024,examinees_2020,examinees_2015
12,Alabama,0.15,0.15,0.12,0.14,28817,27996,21104,23371
22,Alaska,0.14,0.13,0.1,0.11,4462,4110,2823,3187
32,Arizona,0.15,0.14,0.11,0.12,44887,42606,33635,31799
42,Arkansas,0.24,0.23,0.19,0.24,29361,27777,21262,25420
52,California,0.27,0.25,0.23,0.20,407095,388819,355285,316529

In [17]:
participation_states.shape

(51, 9)

In [18]:
participation_states[
    participation_states["state"] == "Florida"
]

,state,participation_2025,participation_2024,participation_2020,participation_2015,examinees_2025,examinees_2024,examinees_2020,examinees_2015
102,Florida,0.25,0.24,0.23,0.23,200790,193422,182712,173984

In [19]:
participation_states = participation_states.reset_index(drop=True)

In [20]:
performance = pd.read_excel(
    "data/raw/ap-admin-report-2025-performance.xlsx"
)

performance.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,AP Performance,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,Total AP Exams,NaN,NaN
4,NaN,NaN,NaN,2025,2024,2020,2015

In [21]:
performance.shape

(3139, 7)

In [22]:
performance.iloc[:10, :20]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,AP Performance,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,Total AP Exams,NaN,NaN
4,NaN,NaN,NaN,2025,2024,2020,2015
5,NaN,National,NaN,NaN,NaN,NaN,NaN
6,NaN,Overall,5,876776,760766,600082,467404
7,NaN,NaN,4,1405669,1203224,865681,721524
8,NaN,NaN,3,1378066,1196541,1083833,964767
9,NaN,NaN,2,979541,991692,872732,885864

In [23]:
performance.iloc[:40, :]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,AP Performance,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,Total AP Exams,NaN,NaN
4,NaN,NaN,NaN,2025,2024,2020,2015
5,NaN,National,NaN,NaN,NaN,NaN,NaN
6,NaN,Overall,5,876776,760766,600082,467404
7,NaN,NaN,4,1405669,1203224,865681,721524
8,NaN,NaN,3,1378066,1196541,1083833,964767
9,NaN,NaN,2,979541,991692,872732,885864
10,NaN,NaN,1,579719,712921,655469,816790
11,NaN,NaN,Total,5219771,4865144,4077797,3856349
12,NaN,NaN,Mean Score,3.2,3.063148,2.97,2.78
13,NaN,By examinee race/ethnicity,NaN,NaN,,NaN,NaN
14,NaN,Asian,5,269160,239807,162746,116197
15,NaN,NaN,4,302405,264740,173196,129818
16,NaN,NaN,3,221428,198316,170429,143901
17,NaN,NaN,2,119272,125427,105983,108257
18,NaN,NaN,1,49204,62742,58357,80737
19,NaN,NaN,Total,961469,891032,670711,578910
20,NaN,NaN,Mean Score,3.65,3.55,3.41,3.16
21,NaN,Hispanic/Latino,5,109681,93473,90420,52361
22,NaN,NaN,4,245865,203699,145916,93369
23,NaN,NaN,3,330052,271166,212860,140557
24,NaN,NaN,2,319052,301144,215041,178554
25,NaN,NaN,1,260400,300223,221948,243776
26,NaN,NaN,Total,1265050,1169705,886185,708617
27,NaN,NaN,Mean Score,2.7,2.56,2.63,2.34
28,NaN,White,5,371755,328928,282109,266137
29,NaN,NaN,4,643780,568409,445415,435902
30,NaN,NaN,3,592642,543361,557098,574604
31,NaN,NaN,2,348027,384876,414405,463022
32,NaN,NaN,1,129377,181002,241930,306413
33,NaN,NaN,Total,2085581,2006576,1940957,2046078
34,NaN,NaN,Mean Score,3.37,3.24,3.06,2.95
35,NaN,Black or African American,5,21233,16995,11779,9170
36,NaN,NaN,4,62229,47578,28078,24088
37,NaN,NaN,3,96028,72909,53702,49367
38,NaN,NaN,2,101127,92536,65554,77397
39,NaN,NaN,1,90802,111009,78462,124276

In [24]:
performance = pd.read_excel(
    "data/raw/ap-admin-report-2025-performance.xlsx",
    header=None
)

performance.columns = [
    "blank",
    "state_or_group",
    "score",
    "2025",
    "2024",
    "2020",
    "2015"
]

performance.head(15)

,blank,state_or_group,score,2025,2024,2020,2015
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,AP Performance,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,Total AP Exams,NaN,NaN
5,NaN,NaN,NaN,2025,2024,2020,2015
6,NaN,National,NaN,NaN,NaN,NaN,NaN
7,NaN,Overall,5,876776,760766,600082,467404
8,NaN,NaN,4,1405669,1203224,865681,721524
9,NaN,NaN,3,1378066,1196541,1083833,964767
10,NaN,NaN,2,979541,991692,872732,885864
11,NaN,NaN,1,579719,712921,655469,816790
12,NaN,NaN,Total,5219771,4865144,4077797,3856349
13,NaN,NaN,Mean Score,3.2,3.063148,2.97,2.78
14,NaN,By examinee race/ethnicity,NaN,NaN,,NaN,NaN

In [25]:
state_rows = performance[
    performance["state_or_group"].isin(states)
]

state_rows[["state_or_group"]].head(10)

           state_or_group
66                Alabama
126                Alaska
186               Arizona
246              Arkansas
306            California
366              Colorado
426           Connecticut
486              Delaware
546  District of Columbia
606               Florida

In [26]:
state_rows.shape

(51, 7)

In [27]:

florida_index = state_rows[
    state_rows["state_or_group"] == "Florida"
].index[0]

florida_index

606

In [28]:
performance.loc[florida_index:florida_index + 8]

,blank,state_or_group,score,2025,2024,2020,2015
606,NaN,Florida,NaN,NaN,NaN,NaN,NaN
607,NaN,Overall,5,50158,44293,40920,27503
608,NaN,NaN,4,97354,83395,65473,51712
609,NaN,NaN,3,109990,96085,89454,78167
610,NaN,NaN,2,81647,80510,72694,81273
611,NaN,NaN,1,45078,53443,59249,87729
612,NaN,NaN,Total,384227,357726,327790,326384
613,NaN,NaN,Mean Score,3.07,2.96,2.87,2.54
614,NaN,By examinee race/ethnicity,NaN,NaN,NaN,,NaN

In [29]:
performance_records = []

for state in states:
    state_index = performance[
        performance["state_or_group"] == state
    ].index[0]

    block = performance.loc[state_index + 1:state_index + 6]

    record = {
        "state": state,
        "score5_2025": block.iloc[0]["2025"],
        "score4_2025": block.iloc[1]["2025"],
        "score3_2025": block.iloc[2]["2025"],
        "score2_2025": block.iloc[3]["2025"],
        "score1_2025": block.iloc[4]["2025"],
        "total_exams_2025": block.iloc[5]["2025"]
    }

    performance_records.append(record)

In [30]:
performance_states = pd.DataFrame(performance_records)
performance_states.shape

(51, 7)

In [31]:
performance_states = pd.DataFrame(performance_records)

performance_states.head()

,state,score5_2025,score4_2025,score3_2025,score2_2025,score1_2025,total_exams_2025
0,Alabama,5902,11959,15451,12222,8406,53940
1,Alaska,784,1827,2530,1758,714,7613
2,Arizona,14456,23605,22629,16477,8979,86146
3,Arkansas,3949,9842,13779,13269,10744,51583
4,California,151990,218410,203879,148207,89798,812284

In [32]:
performance_states.shape

(51, 7)

In [33]:
performance_states[
    performance_states["state"] == "Florida"
]

,state,score5_2025,score4_2025,score3_2025,score2_2025,score1_2025,total_exams_2025
9,Florida,50158,97354,109990,81647,45078,384227

In [34]:
performance_states["pass_rate_2025"] = (
    performance_states["score5_2025"]
    + performance_states["score4_2025"]
    + performance_states["score3_2025"]
) / performance_states["total_exams_2025"]

In [35]:
performance_states["high_score_rate_2025"] = (
    performance_states["score5_2025"]
    + performance_states["score4_2025"]
) / performance_states["total_exams_2025"]

In [36]:
performance_states[
    performance_states["state"] == "Florida"
]

,state,score5_2025,score4_2025,score3_2025,score2_2025,score1_2025,total_exams_2025,pass_rate_2025,high_score_rate_2025
9,Florida,50158,97354,109990,81647,45078,384227,0.670182,0.383919

In [37]:
ap_data = pd.merge(
    participation_states,
    performance_states,
    on="state"
)

ap_data.head()

,state,participation_2025,participation_2024,participation_2020,participation_2015,examinees_2025,examinees_2024,examinees_2020,examinees_2015,score5_2025,score4_2025,score3_2025,score2_2025,score1_2025,total_exams_2025,pass_rate_2025,high_score_rate_2025
0,Alabama,0.15,0.15,0.12,0.14,28817,27996,21104,23371,5902,11959,15451,12222,8406,53940,0.617575,0.331127
1,Alaska,0.14,0.13,0.1,0.11,4462,4110,2823,3187,784,1827,2530,1758,714,7613,0.675292,0.342966
2,Arizona,0.15,0.14,0.11,0.12,44887,42606,33635,31799,14456,23605,22629,16477,8979,86146,0.704502,0.441820
3,Arkansas,0.24,0.23,0.19,0.24,29361,27777,21262,25420,3949,9842,13779,13269,10744,51583,0.534478,0.267356
4,California,0.27,0.25,0.23,0.20,407095,388819,355285,316529,151990,218410,203879,148207,89798,812284,0.706993,0.455998

In [38]:
ap_data.shape

(51, 17)

In [39]:
ap_data[
    ap_data["state"] == "Florida"
]

,state,participation_2025,participation_2024,participation_2020,participation_2015,examinees_2025,examinees_2024,examinees_2020,examinees_2015,score5_2025,score4_2025,score3_2025,score2_2025,score1_2025,total_exams_2025,pass_rate_2025,high_score_rate_2025
9,Florida,0.25,0.24,0.23,0.23,200790,193422,182712,173984,50158,97354,109990,81647,45078,384227,0.670182,0.383919

In [40]:
ap_data["exams_per_examinee_2025"] = (
    ap_data["total_exams_2025"]
    / ap_data["examinees_2025"]
)

In [41]:
ap_data[
    [
        "state",
        "participation_2025",
        "pass_rate_2025",
        "high_score_rate_2025",
        "exams_per_examinee_2025"
    ]
].head(10)

,state,participation_2025,pass_rate_2025,high_score_rate_2025,exams_per_examinee_2025
0,Alabama,0.15,0.617575,0.331127,1.871812
1,Alaska,0.14,0.675292,0.342966,1.706186
2,Arizona,0.15,0.704502,0.441820,1.919175
3,Arkansas,0.24,0.534478,0.267356,1.756854
4,California,0.27,0.706993,0.455998,1.995318
5,Colorado,0.23,0.724636,0.447994,1.77067
6,Connecticut,0.26,0.786879,0.538685,1.935101
7,Delaware,0.19,0.649231,0.363310,1.760738
8,District of Columbia,0.34,0.552174,0.343671,1.866546
9,Florida,0.25,0.670182,0.383919,1.913576

In [42]:
policy_data = pd.DataFrame({
    "state": states
})

policy_data.head()

        state
0     Alabama
1      Alaska
2     Arizona
3    Arkansas
4  California

In [43]:
policy_data.shape

(51, 1)

In [44]:
{
    "state": states
}

{'state': ['Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'District of Columbia',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming']}

In [45]:
policy_data["teacher_performance_incentive"] = 0
policy_data["school_performance_incentive"] = 0
policy_data["participation_incentive"] = 0
policy_data["teacher_training"] = 0
policy_data["exam_fee_support"] = 0
policy_data["access_support"] = 0
policy_data["policy_notes"] = ""

In [46]:
policy_data.shape

(51, 8)

In [47]:
policy_columns = [
    "performance_incentive",
    "participation_incentive",
    "teacher_training",
    "exam_fee_support",
    "access_support",
    "accountability"
]

In [48]:
policy_data = pd.DataFrame({"state": states})

for column in policy_columns:
    policy_data[column] = 0

policy_data["policy_notes"] = ""
policy_data.head()

,state,performance_incentive,participation_incentive,teacher_training,exam_fee_support,access_support,accountability,policy_notes
0,Alabama,0,0,0,0,0,0,
1,Alaska,0,0,0,0,0,0,
2,Arizona,0,0,0,0,0,0,
3,Arkansas,0,0,0,0,0,0,
4,California,0,0,0,0,0,0,

In [49]:
policy_data = pd.read_csv(
    "data/raw/ap_policies_2016.csv"
)

policy_data.head()

,state,performance_incentive,participation_incentive,teacher_training,exam_fee_support,access_support,accountability,policy_notes
0,Alabama,0,0,0,1,1,0,State-supported AP exam fee reduction and stat...
1,Alaska,0,0,0,0,0,0,NaN
2,Arizona,0,0,0,0,0,0,NaN
3,Arkansas,1,0,1,1,1,1,Schools could receive up to $50 for each AP ex...
4,California,0,0,1,0,1,1,"AP accountability/reporting, teacher professio..."

In [50]:
policy_data.shape

(51, 8)

In [66]:
final_data = ap_data.merge(
    policy_data,
    on="state",
    how="inner"
)

final_data.shape

(51, 25)

In [67]:
state_abbreviations = {
    "Alabama": "AL", "Alaska": "AK", "Arizona": "AZ", "Arkansas": "AR",
    "California": "CA", "Colorado": "CO", "Connecticut": "CT", "Delaware": "DE",
    "District of Columbia": "DC", "Florida": "FL", "Georgia": "GA", "Hawaii": "HI",
    "Idaho": "ID", "Illinois": "IL", "Indiana": "IN", "Iowa": "IA",
    "Kansas": "KS", "Kentucky": "KY", "Louisiana": "LA", "Maine": "ME",
    "Maryland": "MD", "Massachusetts": "MA", "Michigan": "MI", "Minnesota": "MN",
    "Mississippi": "MS", "Missouri": "MO", "Montana": "MT", "Nebraska": "NE",
    "Nevada": "NV", "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM",
    "New York": "NY", "North Carolina": "NC", "North Dakota": "ND", "Ohio": "OH",
    "Oklahoma": "OK", "Oregon": "OR", "Pennsylvania": "PA", "Rhode Island": "RI",
    "South Carolina": "SC", "South Dakota": "SD", "Tennessee": "TN", "Texas": "TX",
    "Utah": "UT", "Vermont": "VT", "Virginia": "VA", "Washington": "WA",
    "West Virginia": "WV", "Wisconsin": "WI", "Wyoming": "WY"
}

final_data["state_abbr"] = final_data["state"].map(state_abbreviations)

In [68]:
final_data[["state", "state_abbr"]].head()

        state state_abbr
0     Alabama         AL
1      Alaska         AK
2     Arizona         AZ
3    Arkansas         AR
4  California         CA

In [69]:
final_data[
    [
        "state",
        "state_abbr",
        "participation_2025",
        "pass_rate_2025",
        "performance_incentive",
        "participation_incentive",
        "teacher_training",
        "exam_fee_support",
        "access_support",
        "accountability"
    ]
].head(10)

,state,state_abbr,participation_2025,pass_rate_2025,performance_incentive,participation_incentive,teacher_training,exam_fee_support,access_support,accountability
0,Alabama,AL,0.15,0.617575,0,0,0,1,1,0
1,Alaska,AK,0.14,0.675292,0,0,0,0,0,0
2,Arizona,AZ,0.15,0.704502,0,0,0,0,0,0
3,Arkansas,AR,0.24,0.534478,1,0,1,1,1,1
4,California,CA,0.27,0.706993,0,0,1,0,1,1
5,Colorado,CO,0.23,0.724636,0,1,1,1,1,1
6,Connecticut,CT,0.26,0.786879,0,0,1,1,0,1
7,Delaware,DE,0.19,0.649231,0,0,0,1,1,0
8,District of Columbia,DC,0.34,0.552174,0,0,0,0,0,0
9,Florida,FL,0.25,0.670182,1,0,1,0,1,1

In [70]:
final_data[
    [
        "participation_2025",
        "pass_rate_2025",
        "performance_incentive",
        "participation_incentive",
        "teacher_training",
        "exam_fee_support",
        "access_support",
        "accountability"
    ]
].isna().sum()

participation_2025         0
pass_rate_2025             0
performance_incentive      0
participation_incentive    0
teacher_training           0
exam_fee_support           0
access_support             0
accountability             0
dtype: int64

In [71]:
final_data.to_csv(
    "data/processed/ap_state_data.csv",
    index=False
)

In [72]:
from pathlib import Path

Path("data/processed/ap_state_data.csv").exists()

True

In [73]:
final_data.shape

(51, 26)

final_data.to_csv(
    "data/processed/ap_state_data.csv",
    index=False
)

In [62]:
print("I reached the bottom")

I reached the bottom

In [63]:
1+1

2

In [64]:
1+1

2

In [65]:
print("hello")

hello